name: firebase_in_app_messaging
description: Flutter plugin for Firebase In-App Messaging.
version: 0.6.0+5
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging

false_secrets:
  - example/**

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_core:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: fix/messaging
  firebase_core_platform_interface: ^4.2.3
  firebase_in_app_messaging_platform_interface: ^0.2.0+5
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: null
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.inappmessaging
        pluginClass: FirebaseInAppMessagingPlugin
      ios:
        pluginClass: FirebaseInAppMessagingPlugin
