name: firebase_remote_config_web
description: The web implementation of firebase_remote_config
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_web

version: 1.0.3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_core:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: fix/messaging
  firebase_core_web:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: fix/messaging
  firebase_remote_config_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_remote_config/firebase_remote_config_platform_interface
      ref: fix/messaging
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: 0.6.2

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: fix/messaging
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseRemoteConfigWeb
        fileName: firebase_remote_config_web.dart
