name: firebase_crashlytics_platform_interface
description: A common platform interface for the firebase_crashlytics plugin.
version: 3.1.11
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics_platform_interface

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  collection: ^1.15.0
  firebase_core:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: fix/messaging
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.3
  plugin_platform_interface: 1.0.3

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: fix/messaging
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
