name: firebase_performance_web
description: A new Flutter package project.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance/firebase_performance_web
version: 0.1.0+3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase: 8.0.0
  firebase_core:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: fix/messaging
  firebase_core_web:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: fix/messaging
  firebase_performance_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_performance/firebase_performance_platform_interface
      ref: fix/messaging
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
