name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 2.2.5

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  firebase_core:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: fix/messaging
  firebase_core_web:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: fix/messaging
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_platform_interface
      ref: fix/messaging
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: 0.6.2
  meta: 1.3.0-nullsafety.3

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/markokarapandzic/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: fix/messaging
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
